// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApAzm6Xd_dghtqTxbqY761x8SYDN6OPgA',
    appId: '1:975496563699:android:6e5e2c43be421d40eae086',
    messagingSenderId: '975496563699',
    projectId: 'biodigester-38777',
    databaseURL: 'https://biodigester-38777-default-rtdb.firebaseio.com',
    storageBucket: 'biodigester-38777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCr9n6fCya_Nj3N_ngubHSEftv1UErtw',
    appId: '1:975496563699:ios:1588a2523dd1fedaeae086',
    messagingSenderId: '975496563699',
    projectId: 'biodigester-38777',
    databaseURL: 'https://biodigester-38777-default-rtdb.firebaseio.com',
    storageBucket: 'biodigester-38777.firebasestorage.app',
    iosBundleId: 'com.example.pblBiodigester',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1OU2VwsMNBhZkb4InH_tAJeTpwrDSdwI',
    appId: '1:975496563699:web:17f9ca1a11c1f169eae086',
    messagingSenderId: '975496563699',
    projectId: 'biodigester-38777',
    authDomain: 'biodigester-38777.firebaseapp.com',
    databaseURL: 'https://biodigester-38777-default-rtdb.firebaseio.com',
    storageBucket: 'biodigester-38777.firebasestorage.app',
    measurementId: 'G-Y1553Z4MG9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCr9n6fCya_Nj3N_ngubHSEftv1UErtw',
    appId: '1:975496563699:ios:1588a2523dd1fedaeae086',
    messagingSenderId: '975496563699',
    projectId: 'biodigester-38777',
    databaseURL: 'https://biodigester-38777-default-rtdb.firebaseio.com',
    storageBucket: 'biodigester-38777.firebasestorage.app',
    iosBundleId: 'com.example.pblBiodigester',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1OU2VwsMNBhZkb4InH_tAJeTpwrDSdwI',
    appId: '1:975496563699:web:1021895a6e309fb9eae086',
    messagingSenderId: '975496563699',
    projectId: 'biodigester-38777',
    authDomain: 'biodigester-38777.firebaseapp.com',
    databaseURL: 'https://biodigester-38777-default-rtdb.firebaseio.com',
    storageBucket: 'biodigester-38777.firebasestorage.app',
    measurementId: 'G-CPMTVXYZJ5',
  );

}