version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bio_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: biodigester
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  fastapi_app:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mosquitto
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/biodigester
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped

volumes:
  postgres_data:
